/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ButtonPanelTransaksi.java
 *
 * Created on Apr 30, 2009, 11:25:30 AM
 */

package com.artivisi.pos.ui.toolbar;

import javax.swing.JButton;

/**
 *
 * @author ifnu
 */
public class ButtonPanelTransaksi extends javax.swing.JPanel {

    /** Creates new form ButtonPanelTransaksi */
    public ButtonPanelTransaksi() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        btnTambah.setText("Tambah");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");

        btnBatal.setText("Batal");

        btnCari.setText("Cari");

        btnKeluar.setText("Exit");

        btnCetak.setText("Cetak");

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah)
                .addGap(9, 9, 9)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnCari, btnCetak, btnEdit, btnHapus, btnKeluar, btnSimpan, btnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnHapusActionPerformed

    public JButton getBtnBatal() {
        return btnBatal;
    }

    public JButton getBtnCari() {
        return btnCari;
    }


    public JButton getBtnCetak() {
        return btnCetak;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public JButton getBtnExit() {
        return btnKeluar;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnTambah() {
        return btnTambah;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnKeluar() {
        return btnKeluar;
    }

    public void kondisiAwal() {
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        btnCari.setEnabled(true);
        btnCetak.setEnabled(false);
    }

    public void kondisiTambah() {
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        btnCari.setEnabled(false);
        btnCetak.setEnabled(false);
    }

    public void kondisiCari() {
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(false);
        btnCari.setEnabled(false);
        btnCetak.setEnabled(true);
    }
    public void kondisiEdit() {
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        btnCari.setEnabled(false);
        btnCetak.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    // End of variables declaration//GEN-END:variables

}
